### PR TITLE
Add ESO argoCD app to infra

### PR DESCRIPTION
**Pull request by dystewart**

### CODE REVIEW

**Comment by dystewart** [comment]
see [https://github.com/OCP-on-NERC/nerc-ocp-config/pull/33](https://github.com/OCP-on-NERC/nerc-ocp-config/pull/33)

**Comment by joachimweyl** [comment]
@dystewart is this still accurate now that we went with [PR34](https://github.com/OCP-on-NERC/nerc-ocp-config/pull/34) instead of PR33?

**Comment by dystewart** [comment]
Actually @larsks given that there isn't an external secrets base folder where should I point the argoCD app for external secrets? Shouldn't we have a base folder with overlays since ESO is per cluster?
Like in [operate-first](https://github.com/operate-first/apps/tree/master/external-secrets/overlays)

**Comment by larsks** [comment]
Since we've installed ESO via an operator we don't have a base app folder for it. Right now, the ESO config is in the cluster overlay (`cluster-scope/overlays/nerc-ocp-infra/kustomization.yaml`). I'm not sure what the right solution is here: since we're not installing CRDs or other application deployment manifests, I'm not sure we need the top-level app directory. What do you think?

**Comment by dystewart** [comment]
I think given that there aren't any other resources being deployed there's not really a need for the base folder. Anyways the ESO deployments will be the same regardless of cluster. So I suppose the argoCD path should just point to the resource bundle instead? Since the operatorConfig is in there?

**Review by naved001 — COMMENTED** [review]
I think we should close this, since whatever we need for ESO is being deployed by the app managing `cluster-scope/overlays/nerc-ocp-infra`.

**Comment by joachimweyl** [comment]
Closing. We can always reopen it if we decide we need part of it.

**Pull request closed without merging**
