### PR TITLE
xdmod deploy

### PR DESCRIPTION
**Pull request by rob-baron**
I am doing it this way for now, however, now that I see the process 
this implies chages that need to be made in the xdmod-cntr project.  

I am doing this like this here as I don't quite see any other way of 
doing this as currently the container is built using the build configuration 
separately from the project being deployed.  Useful for development, but 
not for deploying in production.

Also, am specifying a particular commit in the bc-xdmod and expect
to customize the xdmod-init.json.

### CODE REVIEW

**Comment by rob-baron** [comment]
@joachimweyl I am sure once I actually look into this problem that it will be clear.  I do use yaml linters in vscode to catch this type of problem while editing.

**Comment by rob-baron** [comment]
@joachimweyl it was obvious once I used yamllint from the command line.  As I state in the commit message, yamllint seems to be overly strict, however, this is the process that we are using.

Also makes sense that I didn't see that yamllint failed as the workflow needs to be approved by someone.

**Comment by joachimweyl** [comment]
Just to confirm this closes [Issue 57](https://github.com/CCI-MOC/xdmod-cntr/issues/57)? If so let's add to the commit message "Closes CCI-MOC/xdmod-cntr/issues/57".

**Review by larsks — CHANGES_REQUESTED** [review]
This repository is meant to contain just ArgoCD application manifests ([like this](https://github.com/OCP-on-NERC/nerc-ocp-apps/blob/main/clusters/nerc-ocp-infra/vault/application.yaml)). The actual deployment manifests for xdmod are meant to come from another repository (which you specify in the application manifest).

In this case, I imagine that would be the [xdmod-cntr](https://github.com/CCI-MOC/xdmod-cntr/) repository. If for someone reason that isn't appropriate, we could create a new top-level directory in the [config repository](https://github.com/OCP-on-NERC/nerc-ocp-config/) (which should follow the same layout you'll find there for the `vault`, `acm`, and `cluster-scope` directories: `<appname>/base`, `<appname>/overlays/<clustername>`, etc).

So we should close this PR and open a new one that contains the appropriate ArgoCD application.

**Comment by larsks** [comment]
I would also like to refer again to our [standards for the structure of commit messages](https://github.com/CCI-MOC/ops-docs/blob/master/policies/0007-pull-requests.md#what-makes-a-good-pull-request-1), because that makes it easier to browse commits both locally and in the github ui.

**Comment by larsks** [comment]
>  fixed the issues that yamllint had with the yaml, though I suspect it is overly strict as this yaml worked for deploying on ocp-staging.

The purpose of linting isn't just to ensure "it works", but also to a consistent formatting in our code and documentation. For example, if we adopt `black` for auto-formatting code in a Python project, a pre-commit check will reject perfectly valid code because it doesn't meet `black` formatting preferences. The goal here is to make code from multiple authors (potentially across multiple projects) as similar as possible.

I think the disconnect here between the online checks and what you saw locally were caused by two things:

(1) If you're running `pre-commit` manually, to reproduce the behavior of the CI checks you need to run `pre-commit run --all-files`; without `--all-files`, `pre-commit` only checks files modified by the current commit.

(2) If you're only running `yamllint`, then you're ignoring the other checks that are also implemented by the `pre-commit` configuration.

(2) It sounds like you haven't configured your pre-commit checks locally; with this enabled, you would have caught these issues as you made each commit. You can enable the commit checks by simply running `pre-commit install`.

**Comment by rob-baron** [comment]
specifically what I was referring to was that I couldn't find a single way to comment out a section of yaml.  Specifically:

      volumes:
        - name: vol-xdmod-conf
          persistentVolumeClaim:
            claimName: pvc-xdmod-conf
        - name: vol-clouds-yaml
          persistentVolumeClaim:
            claimName: pvc-clouds-yaml
        ...
      # - name: vol-nerc-shift-0-cred
      #   secret:
      #     secretName: xdmod-os-app-cred
      
yamllint didn't like the comments to aligned under the "volumes" section, nor did it like when I moved them over to buy under the - name section, nor did it like when I move the comments to be under the "claimName".  I just removed the comments as it is currently dead code.

I have kept this in the main repository as it reminds me how I handled secrets that justin will eventually provide.

Perhaps I need to do something else besides include this type of semi-dynamic information in the deployment

**Comment by rob-baron** [comment]
ok larks, we will close this and I will restructure the manifests in the xdmod-cntr repository

**Pull request closed without merging**
