### PR TITLE
Adding ArgoCD Application for nerc-ocp-obs Observability cluster

### PR DESCRIPTION
**Pull request by computate**
This will manage the cluster-scope for the new Observability cluster.

fixes https://github.com/nerc-project/operations/issues/309

### CODE REVIEW

**Review by schwesig — APPROVED** [review]
thanks for the PR @computate. As we talked about earlier. Approved.

**Comment by schwesig** [comment]
@schwesig

**Review by larsks — CHANGES_REQUESTED** [review]
There is a spelling error in the commit title and the PR title. s/Obsebrvability/Observability/

**Comment by computate** [comment]
Oops, should be fixed now @larsks , thanks!

**Review by jtriley — APPROVED** [review]

**Review by larsks — APPROVED** [review]

**Pull request merged**
