### PR TITLE
Adding new RHODS images for Ecological Forecasting and Smart Village projects

### PR DESCRIPTION
**Pull request by computate**
# Add PEcAn Ecological Forecasting ArgoCD App to Prod cluster
    
Adding new RHODS images for the
software-application-innovation-lab-sail-projects-fcd6dfa namespace

- Datascience + RStudio JupyterLab Notebook image
- PEcAn Unconstrained Forecast JupyterLab Notebook image

# Add Smart Village ArgoCD App to Prod cluster

Adding new RHODS images for the smart-village-faeeb6c namespace

- Smart Village Traffic Light Controller SUMO Python RHODS image

### CODE REVIEW

**Comment by jtriley** [comment]
I've been doing some research on how to best enable users to manage these custom images themselves in an effort to keep cluster admins out of the loop. I've asked the folks in the opendatahub slack whether it's possible to load custom images from user namespaces vs the `redhat-ods-applications` namespace. Assuming that's not possible, we might want to consider a custom role and role binding that allows users to create imagestream resources in the `redhat-ods-applications` namespace.

**Comment by jtriley** [comment]
From the opendatahub slack:

> At the moment all the IS for custom images must be in this namespace. It's on the roadmap to have per-project custom images, but we're not there yet...

They suggested filing a feature request for support for loading custom imagesreams/BYON imagestreams from projects/namespaces users have permissions to.

Given this I think we might be best off giving users permissions (via custom role and binding) to create imagestreams in the `redhat-ods-applications` namespace vs having to manage them in this repo.

**Review by jtriley — APPROVED** [review]

**Review by larsks — APPROVED** [review]
I wonder if onboarding end user applications to our infra argocd instance is really the right thing to do? I would argue that if we want to offer argocd as a service for non-admins, we should run a separate instance on the prod cluster.

Approving this for now, because I don't want to block anything, but I will create an issue to discuss this.

**Comment by jtriley** [comment]
This suggests it won't get overridden ```
$ oc explain Application.spec.destination
   ...
   
   namespace    <string>
     Namespace specifies the target namespace for the application's resources.
     The namespace will only be set for namespace-scoped resources that have not
     set a value for .metadata.namespace
```

**Pull request merged**
